In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML_datasets/imdb_dataset/IMDB Dataset.csv')

In [ ]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
df.iloc[0,0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [ ]:
X = df.iloc[:,0]
y=df.iloc[:,1]

In [ ]:
df.sentiment.value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [ ]:
X.shape,y.shape

((50000,), (50000,))

In [ ]:
y= np.where(y=='positive',1,0)

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import regex as re

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
sw = stopwords.words('english')
ps = PorterStemmer()

In [ ]:
def clean_sents(sent):
  clean_sent = re.sub('[^a-zA-Z]',' ',sent)
  clean_sent = clean_sent.lower()
  clean_sent = clean_sent.split()
  clean_sent = [ps.stem(x) for x in clean_sent if x not in sw]
  clean_sent = ' '.join(clean_sent)
  return clean_sent

In [ ]:
def clean_doc(doc):
  corpus = []
  for sent in doc:
    clean_sent = clean_sents(sent)
    corpus.append(clean_sent)
  return corpus

In [ ]:
corpus = clean_doc(X)

In [ ]:
# corpus_file ='/content/drive/MyDrive/ML_datasets/imdb_dataset/corpus.pkl'
# with open(corpus_file,'wb') as file:
#   pickle.dump(corpus,file)

In [ ]:
# with open('/content/drive/MyDrive/ML_datasets/imdb_dataset/corpus.pkl','rb') as file:
#   corpus = pickle.load(file)

In [ ]:
len(corpus)

50000

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(corpus,y,test_size=0.2,random_state=42)

In [ ]:
len(X_train),len(X_test),len(y_train),len(y_test)

(40000, 10000, 40000, 10000)

In [ ]:
cv = CountVectorizer(ngram_range=(2,2),stop_words='english')
X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

In [ ]:
tf = TfidfVectorizer()
X_train_tf = tf.fit_transform(X_train)
X_test_tf = tf.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
def model(model):
  model.fit(X_train_cv,y_train)
  y_pred =model.predict(X_test_cv)
  print(f"the model is {model}")
  print(f"the accuracy is {accuracy_score(y_test,y_pred)}")
  print(f"confusion matrix : {confusion_matrix(y_test,y_pred)}")
  print(f"classification report: {classification_report(y_test,y_pred)}")

In [ ]:
model(MultinomialNB())

the model is MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
the accuracy is 0.877
confusion matrix : [[4445  516]
 [ 714 4325]]
classification report:               precision    recall  f1-score   support

           0       0.86      0.90      0.88      4961
           1       0.89      0.86      0.88      5039

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000



In [ ]:
model(LogisticRegression())

the model is LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
the accuracy is 0.8639
confusion matrix : [[4144  817]
 [ 544 4495]]
classification report:               precision    recall  f1-score   support

           0       0.88      0.84      0.86      4961
           1       0.85      0.89      0.87      5039

    accuracy                           0.86     10000
   macro avg       0.87      0.86      0.86     10000
weighted avg       0.86      0.86      0.86     10000



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
model(RandomForestClassifier())

the model is RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
the accuracy is 0.8105
confusion matrix : [[3710 1251]
 [ 644 4395]]
classification report:               precision    recall  f1-score   support

           0       0.85      0.75      0.80      4961
           1       0.78      0.87      0.82      5039

    accuracy                           0.81     10000
   macro avg       0.82      0.81      0.81     10000
weighted avg       0.81      0.81      0.81     10000



In [ ]:
def model_tf(model):
  model.fit(X_train_tf,y_train)
  y_pred =model.predict(X_test_tf)
  print(f"the model is {model}")
  print(f"the accuracy is {accuracy_score(y_test,y_pred)}")
  print(f"{confusion_matrix(y_test,y_pred)}")
  print(f"{classification_report(y_test,y_pred)}")

In [ ]:
model_tf(MultinomialNB())

the model is MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
the accuracy is 0.8613
[[4331  630]
 [ 757 4282]]
              precision    recall  f1-score   support

           0       0.85      0.87      0.86      4961
           1       0.87      0.85      0.86      5039

    accuracy                           0.86     10000
   macro avg       0.86      0.86      0.86     10000
weighted avg       0.86      0.86      0.86     10000



In [ ]:
model_tf(LogisticRegression())

the model is LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
the accuracy is 0.8924
[[4345  616]
 [ 460 4579]]
              precision    recall  f1-score   support

           0       0.90      0.88      0.89      4961
           1       0.88      0.91      0.89      5039

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



In [ ]:
lr_model = LogisticRegression().fit(X_train_tf,y_train)

In [ ]:
# file_name ="imdb_lr.pkl"
# with open(file_name,'wb') as file:
#   pickle.dump(lr_model,file=file)

In [ ]:
# with open('/content/drive/MyDrive/ML_datasets/imdb_dataset/imdb_lr.pkl', 'rb') as file:  
#     model_lr = pickle.load(file)